# Optional: Create a GitHub PR with snapshot of output files.
import os, subprocess, json, sys, requests, time

GITHUB_PAT = os.environ.get('GITHUB_PAT')  # optional
if not GITHUB_PAT:
    print('GITHUB_PAT not set; skipping PR creation.')
    sys.exit(0)

branch = 'auto/snapshot-' + time.strftime('%Y%m%d%H%M%S')
subprocess.run(['git', 'checkout', '-b', branch], check=False)
subprocess.run(['git', 'add', 'output'], check=False)
subprocess.run(['git', 'commit', '-m', 'Auto snapshot of intelligence outputs'], check=False)
subprocess.run(['git', 'push', '--set-upstream', 'origin', branch], check=False)

repo = os.environ.get('GITHUB_REPOSITORY')  # e.g. user/repo
if not repo:
    print('GITHUB_REPOSITORY not found; cannot create PR.')
    sys.exit(0)
url = f'https://api.github.com/repos/{repo}/pulls'
headers = {'Authorization': f'token {GITHUB_PAT}', 'Accept': 'application/vnd.github+json'}
data = {'title':'Auto snapshot of intelligence outputs','head':branch,'base':'main','body':'Automated snapshot generated by workflow.'}
r = requests.post(url, headers=headers, json=data)
print('PR response', r.status_code, r.text)
